spring:
  application:
    name: enygma
  cache:
    type: redis
  redis:
    host: localhost
    port: ${REDIS_PORT:6379}

server:
  port: ${PORT:8001}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
          - httptrace
