spring:
  application:
    name: googledict
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    url: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
          - httptrace